# Generated by Django 5.1.4 on 2024-12-30 20:54

import django.db.models.deletion
import user.managers.manager_user
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(verbose_name="Имя")),
                ("last_name", models.CharField(verbose_name="Фамилия")),
                ("patronymic", models.CharField(blank=True, verbose_name="Отчество")),
                (
                    "password",
                    models.CharField(max_length=15, verbose_name="Пароль от аккаунта"),
                ),
                (
                    "mail",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Электронная почта"
                    ),
                ),
                ("phone", models.CharField(blank=True, verbose_name="Номер телефона")),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        blank=True, verbose_name="Возраст"
                    ),
                ),
                (
                    "full_name_teacher",
                    models.CharField(blank=True, verbose_name="ФИО преподавателя"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, upload_to="", verbose_name="Фото профиля"
                    ),
                ),
            ],
            options={
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенты",
                "db_table": "students",
                "db_table_comment": "Table with student accounts.",
            },
        ),
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about_teacher",
                    models.CharField(max_length=350, verbose_name="О себе"),
                ),
                ("experience", models.CharField(verbose_name="Опыт преподавания")),
                ("age", models.PositiveSmallIntegerField(verbose_name="Возраст")),
                (
                    "avatar",
                    models.ImageField(upload_to="", verbose_name="Фото профиля"),
                ),
            ],
            options={
                "verbose_name": "преподаватель",
                "verbose_name_plural": "преподаватели",
                "db_table": "teachers",
                "db_table_comment": "Table with teacher accounts.",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("first_name", models.CharField(verbose_name="Имя")),
                ("last_name", models.CharField(verbose_name="Фамилия")),
                ("patronymic", models.CharField(blank=True, verbose_name="Отчество")),
                (
                    "password",
                    models.CharField(max_length=15, verbose_name="Пароль от аккаунта"),
                ),
                (
                    "mail",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Электронная почта"
                    ),
                ),
                ("phone", models.CharField(blank=True, verbose_name="Номер телефона")),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.students",
                    ),
                ),
            ],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
                "db_table": "users",
                "db_table_comment": "Table with users.",
            },
            managers=[
                ("objects", user.managers.manager_user.UserManager()),
            ],
        ),
    ]
