# Generated by Django 5.1.4 on 2024-12-22 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(verbose_name="Имя")),
                ("last_name", models.CharField(verbose_name="Фамилия")),
                ("patronymic", models.CharField(verbose_name="Отчество")),
                ("age", models.PositiveSmallIntegerField(verbose_name="Возраст")),
                (
                    "full_name_teacher",
                    models.CharField(verbose_name="ФИО предподавателя"),
                ),
                (
                    "avatar",
                    models.ImageField(upload_to="", verbose_name="Фото профиля"),
                ),
                (
                    "password",
                    models.CharField(max_length=15, verbose_name="Пароль от аккаунта"),
                ),
                (
                    "mail",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                (
                    "phone",
                    models.EmailField(max_length=254, verbose_name="Номер телефона"),
                ),
            ],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
                "db_table": "students",
                "db_table_comment": "Table with student accounts.",
            },
        ),
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(verbose_name="Имя")),
                ("last_name", models.CharField(verbose_name="Фамилия")),
                ("patronymic", models.CharField(verbose_name="Отчество")),
                (
                    "about_teacher",
                    models.CharField(max_length=350, verbose_name="О себе"),
                ),
                ("experience", models.CharField(verbose_name="Опыт предподавания")),
                ("age", models.PositiveSmallIntegerField(verbose_name="Возраст")),
                (
                    "avatar",
                    models.ImageField(upload_to="", verbose_name="Фото профиля"),
                ),
                (
                    "password",
                    models.CharField(max_length=15, verbose_name="Пароль от аккаунта"),
                ),
                (
                    "mail",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                (
                    "phone",
                    models.EmailField(max_length=254, verbose_name="Номер телефона"),
                ),
            ],
            options={
                "verbose_name": "предподаватель",
                "verbose_name_plural": "предподаватели",
                "db_table": "teachers",
                "db_table_comment": "Table with teacher accounts.",
            },
        ),
        migrations.CreateModel(
            name="Lessons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=25, verbose_name="Тема урока")),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime(
                            2024,
                            12,
                            22,
                            18,
                            16,
                            31,
                            814694,
                            tzinfo=datetime.timezone.utc,
                        ),
                        verbose_name="Дата урока",
                    ),
                ),
                (
                    "optional_material",
                    models.FileField(upload_to="", verbose_name="Материал к уроку"),
                ),
                ("teacher_name", models.CharField(verbose_name="ФИО предподавателя")),
                (
                    "link_to_lesson",
                    models.URLField(verbose_name="Ссылка на урок (конференцию)"),
                ),
                (
                    "pupils",
                    models.ManyToManyField(
                        related_name="lessons",
                        to="school.students",
                        verbose_name="Ученики",
                    ),
                ),
            ],
            options={
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
                "db_table": "lessons",
                "db_table_comment": "Table with lessons.",
            },
        ),
    ]
