# Generated by Django 5.1.4 on 2024-12-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lessons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=25, verbose_name="Тема урока")),
                ("date", models.DateField(verbose_name="Дата урока")),
                (
                    "optional_material",
                    models.FileField(upload_to="", verbose_name="Материал к уроку"),
                ),
                ("teacher_name", models.CharField(verbose_name="ФИО преподавателя")),
                (
                    "link_to_lesson",
                    models.URLField(verbose_name="Ссылка на урок (конференцию)"),
                ),
                (
                    "pupils",
                    models.ManyToManyField(
                        related_name="lessons",
                        to="user.students",
                        verbose_name="Ученики",
                    ),
                ),
            ],
            options={
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
                "db_table": "lessons",
                "db_table_comment": "Table with lessons.",
            },
        ),
    ]
